katropine_oauth:
    resource: "@KatropineOauthBundle/Controller/"
    type:     annotation
    prefix:   /api

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

    
katropine_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: KatropineOauthBundle:Security:login }

katropine_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: KatropineOauthBundle:Security:loginCheck }
